### ISSUE TITLE
hubot fitbit approve doesn't seem to work

### ISSUE THREAD

**Issue by gep13** [stephenyeargin/hubot-fitbit-leaders#2]
Hello,

We have just set up this extension in our gitter chatroom, and while the commands for:

```chocobot fitbit register```
```chocobot fitbit leaders```

work just fine, the:

```chocobot fitbit approve```

doesn't seem to work.  I have been having to manually log in and approve the friend requests.  Is this a known issue?

Thanks
Gary

**Comment by stephenyeargin** [comment]
So, I think this is an intermittent API issue, but I can't prove it. I was able to get through locally. We have had similar issues in the past with our integration.

```
stephen> crunchy fitbit approve
crunchy> Approve: Stephen
stephen> crunchy fitbit approve
crunchy> No pending requests.
```

I'm presuming running `hubot fitbit approve` multiple times says that is approving the user over and over again?

**Comment by ferventcoder** [comment]
No. it just doesn't do anything. Didn't dive into the logs but no response was coming back. Although now we are getting a response of `No pending requests` (I also restarted the hubot). So it could be when there are requests it has issues.

**Comment by stephenyeargin** [comment]
I'll leave this open in case anyone else experiences it. Hope at the rest of the script is working out, we enjoy using it.

**Comment by ferventcoder** [comment]
we like it, too. Not completely sure what is causing it.

**Comment by stephenyeargin** [comment]
Closing this off, as the API has changed since (drastically in #7). Please re-file if you run into this again. The latest release, `v2.0.2`, is the latest candidate.
