### ISSUE TITLE
fitbit no longer supports oauth 1.0a

### ISSUE THREAD

**Issue by antisocialdalek** [stephenyeargin/hubot-fitbit-leaders#6]
I'm just starting to get involved with hubot and am just starting to learn coffeescript/javascript/node.js (coming from a PHP/ObjC/Swift background).. it looks like fitbit has now completely depreciated the 1.0a oauth, and now only allows new applications to use oauth2. Any chance someone will take up the challenge to update this module to use oauth2? :)

**Comment by stephenyeargin** [comment]
Blocked by https://github.com/smurthas/fitbit-js/issues/16 -- the underlying package would need to support it first, then this would need to be refactored to support that one.

**Comment by antisocialdalek** [comment]
Sorry, didn't see that someone had already opened an issue on this. Thanks for the fast reply!

**Comment by stephenyeargin** [comment]
Nah, that's the bug in the sub-package. This is legit until that other one gets updated. May be a while -- doesn't appear to be a lot of activity on it.

**Comment by stephenyeargin** [comment]
Note that as of this week, the package stopped working altogether. There's [another package](https://github.com/p-m-p/node-fitbit) we could use, but it doesn't have support for `POST` commands (namely, accepting friend requests on behalf of the bot).
